apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scoopp-ingress
  namespace: scoopp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - scoopp.re-cloud.io
      secretName: scoopp-tls
  rules:
    - host: scoopp.re-cloud.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scoopp-frontend
                port:
                  number: 80
