apiVersion: v1
kind: Secret
metadata:
  name: scoopp-secret
  namespace: scoopp
type: Opaque
stringData:
  api_key: "REPLACE"
  brave_api_key: "REPLACE"
  openai_api_key: "REPLACE"
  mail_api_key: "REPLACE"
  s3_access_key: "REPLACE"
  s3_secret_key: "REPLACE"
